### PR TITLE
refactoring for @lemmatum review

### PR DESCRIPTION
**Pull request by StanczakDominik**
I'm working off my laptop and something is off with my ssh keys so I can't just push to your branch right now. But this should give you an opportunity to review these, so it's probably for the best! I took care of the minor stuff and stylistic points, but there's still some stuff in that review you should probably look at.

### CODE REVIEW

**Comment by StanczakDominik** [comment]
I'm seeing test errors on this commit but I can't reproduce them on my machine. This might be some dependency update. Please don't merge yet!

**Comment by StanczakDominik** [comment]
Okay, I understand absolutely nothing. I updated everything I could update and suddenly `Illegal instruction` on running pytest. We might as well merge this, I think. Maybe it's something intermittent. I have no idea.

**Comment by StanczakDominik** [comment]
OH FFS

**Comment by jasperbeckers** [comment]
Nice work! Let's merge this and fix pytest afterwards. I'll wait for your OK.

**Comment by StanczakDominik** [comment]
Go right ahead and merge, I think the test failures were intermittent due to unseeded use of random :D

**Pull request merged**
